### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by System-Glitch** [go-goyave/goyave.dev#6]
The landing page is currently a bit dull and empty, not very "selling" the framework. I would like to rework it to make the framework more appealing.

The new landing page could be similar to the README in terms of content, showcasing the framework's goals and philosophy, the key features, etc.

Inspiration:
- https://tailwindcss.com/
- https://www.framer.com/
- https://www.balena.io/
- https://www.docker.com/
- https://responsively.app/

**Comment by akurtaliqi** [comment]
-> faire des composants (fichiers vue js)
-> après import les composants dans le readme
